version: "1.0.0"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PWD}
    volumes:
      - './data:/data/db'
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PWD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PWD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
